# Generated by Django 2.1.5 on 2019-02-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190114_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
