# Generated by Django 2.1.5 on 2019-02-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190219_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
