# Generated by Django 2.1.5 on 2019-01-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogarticles_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='title_images/'),
        ),
    ]
