# Generated by Django 2.1.5 on 2019-01-26 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190126_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='title_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='title_images/'),
            preserve_default=False,
        ),
    ]
